theme: jekyll-theme-slate
title: Welcome to Jianbin Lin's homepage!
description: I am a senior CS student of the University of Texas as Austin. Currently, I am looking for a full-time job in mid-2020.
